name: UltraHardcore

main: me.spypat.UltraHarcore.UltraHardcore

version: 1.1.0

api-version: 1.14

commands:

   fixbeacon:

      description: Adds beacons to players who already joined.

      usage: /fixbeacon
